name = "cf-analytics"
main = "src/index.ts"
compatibility_date = "2025-08-01"

[[d1_databases]]
binding = "DB" # available in your Worker on env.DB
database_name = "web_analytics"
database_id = "b5df44a0-2495-4255-9283-7a1342726fd9"
